### ISSUE TITLE
aws-node crashes with ipv6 on c5.metal

### ISSUE THREAD

**Issue by matti** [aws/amazon-vpc-cni-k8s#1929]
**What happened**:

eksctl created cluster has aws-node in CrashLoopBackOff on eu-west-1

ami: ami-0f47e499c06cba4fc
managed nodegroup
instance-type c5.metal
network ipv6
image: 602401143452.dkr.ecr.eu-north-1.amazonaws.com/amazon-k8s-cni:v1.10.2-eksbuild.1

**Attach logs**
```
{"level":"info","ts":"2022-03-15T11:55:53.162Z","caller":"entrypoint.sh","msg":"Validating env variables ..."}
{"level":"info","ts":"2022-03-15T11:55:53.163Z","caller":"entrypoint.sh","msg":"Install CNI binaries.."}
{"level":"info","ts":"2022-03-15T11:55:53.178Z","caller":"entrypoint.sh","msg":"Starting IPAM daemon in the background ... "}
{"level":"info","ts":"2022-03-15T11:55:53.179Z","caller":"entrypoint.sh","msg":"Checking for IPAM connectivity ... "}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x39 pc=0x55af3f5a83f8]

goroutine 626 [running]:
github.com/aws/amazon-vpc-cni-k8s/pkg/ipamd.(*IPAMContext).StartNodeIPPoolManager(0xc000944f68)
	/go/src/github.com/aws/amazon-vpc-cni-k8s/pkg/ipamd/ipamd.go:640 +0x18
created by main._main
	/go/src/github.com/aws/amazon-vpc-cni-k8s/cmd/aws-k8s-agent/main.go:64 +0x2bb
{"level":"info","ts":"2022-03-15T11:55:55.188Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-03-15T11:55:57.196Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-03-15T11:55:59.203Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
```

**What you expected to happen**:
No crash

**How to reproduce it (as minimally and precisely as possible)**:
Create a fresh cluster with ipv6, request managed nodes with 96 cores, 192mb ram

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21
- CNI Version amazon-k8s-cni:v1.10.2-eksbuild.1
- OS (e.g: `cat /etc/os-release`): 
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
- Kernel (e.g. `uname -a`):
```
Linux ip-192-168-68-37.eu-north-1.compute.internal 5.4.181-99.354.amzn2.x86_64 #1 SMP Wed Mar 2 18:50:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
- ami: ami-0f47e499c06cba4fc

**Comment by matti** [comment]
and now with another instance c5a.16xlarge it runs just fine in the same cluster

**Comment by matti** [comment]
verified - it *always* crashes on c5.metal instances, works fine on c5.24xlarge and c5a.16xlarge

**Comment by achevuru** [comment]
Were these env variables (`ENABLE_IPv4` and `ENABLE_IPv6`) added after `aws-node` was already in `CrashLoopbackOff`? It should be same as #1854 based on the stack trace you provided - https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.10.2/pkg/ipamd/ipamd.go#L640

**Comment by matti** [comment]
eg. I have the same eksctl created yaml and it works on all other instance types except on c5.metal

**Comment by matti** [comment]
with this ekctl cluster config it should happen as long as instanceSelector returns c5.metal - might need some scaleup to get it: https://github.com/weaveworks/eksctl/issues/4956#issue-1169709391

**Comment by matti** [comment]
just spun up another cluster with c5.metal instance and same behaviour, same stacktrace and envs are set for sure.

```
$ kubectl describe pod -n kube-system aws-node-mqwg7
Name:                 aws-node-mqwg7
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 ip-192-168-85-232.eu-north-1.compute.internal/2a05:d016:dd0:4a02::35ad
Start Time:           Wed, 16 Mar 2022 10:56:57 +0200
Labels:               app.kubernetes.io/name=aws-node
                      controller-revision-hash=fcd885d64
                      k8s-app=aws-node
                      pod-template-generation=3
Annotations:          eksctl.io/restartedAt: 2022-03-15T15:08:22+02:00
                      kubernetes.io/psp: eks.privileged
Status:               Running
IP:                   2a05:d016:dd0:4a02::35ad
IPs:
  IP:           2a05:d016:dd0:4a02::35ad
  IP:           16.16.4.178
Controlled By:  DaemonSet/aws-node
Init Containers:
  aws-vpc-cni-init:
    Container ID:   docker://6cf1ab6eb0eb0860700957e021c139fbc296f30a04767a0dfb24a56c78d0c28f
    Image:          602401143452.dkr.ecr.eu-north-1.amazonaws.com/amazon-k8s-cni-init:v1.10.2-eksbuild.1
    Image ID:       docker-pullable://602401143452.dkr.ecr.eu-north-1.amazonaws.com/amazon-k8s-cni-init@sha256:a5b9f0654b6997a7f20395c6f5a4d9ffa925b84d042177426229b6e8a5a5f8ea
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 16 Mar 2022 10:57:03 +0200
      Finished:     Wed, 16 Mar 2022 10:57:03 +0200
    Ready:          True
    Restart Count:  0
    Environment:
      DISABLE_TCP_EARLY_DEMUX:      false
      ENABLE_IPv6:                  true
      AWS_STS_REGIONAL_ENDPOINTS:   regional
      AWS_DEFAULT_REGION:           eu-north-1
      AWS_REGION:                   eu-north-1
      AWS_ROLE_ARN:                 arn:aws:iam::254324309357:role/eksctl-test-1-addon-vpc-cni-Role1-R8JN8FC9EHA6
      AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    Mounts:
      /host/opt/cni/bin from cni-bin-dir (rw)
      /var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7hzjl (ro)
Containers:
  aws-node:
    Container ID:   docker://0029ab3e926c3629574e679df110e6463195f7194f885c83f4bf13eeca29ee18
    Image:          602401143452.dkr.ecr.eu-north-1.amazonaws.com/amazon-k8s-cni:v1.10.2-eksbuild.1
    Image ID:       docker-pullable://602401143452.dkr.ecr.eu-north-1.amazonaws.com/amazon-k8s-cni@sha256:8c0135371030c6513e05f472dd66aaf7c722459781647150286618f054a4c782
    Port:           61678/TCP
    Host Port:      61678/TCP
    State:          Running
      Started:      Wed, 16 Mar 2022 11:02:04 +0200
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Wed, 16 Mar 2022 11:00:24 +0200
      Finished:     Wed, 16 Mar 2022 11:02:04 +0200
    Ready:          False
    Restart Count:  3
    Requests:
      cpu:      25m
    Liveness:   exec [/app/grpc-health-probe -addr=:50051 -connect-timeout=5s -rpc-timeout=5s] delay=60s timeout=10s period=10s #success=1 #failure=3
    Readiness:  exec [/app/grpc-health-probe -addr=:50051 -connect-timeout=5s -rpc-timeout=5s] delay=1s timeout=10s period=10s #success=1 #failure=3
    Environment:
      ADDITIONAL_ENI_TAGS:                    {}
      AWS_VPC_CNI_NODE_PORT_SUPPORT:          true
      AWS_VPC_ENI_MTU:                        9001
      AWS_VPC_K8S_CNI_CONFIGURE_RPFILTER:     false
      AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG:     false
      AWS_VPC_K8S_CNI_EXTERNALSNAT:           false
      AWS_VPC_K8S_CNI_LOGLEVEL:               DEBUG
      AWS_VPC_K8S_CNI_LOG_FILE:               /host/var/log/aws-routed-eni/ipamd.log
      AWS_VPC_K8S_CNI_RANDOMIZESNAT:          prng
      AWS_VPC_K8S_CNI_VETHPREFIX:             eni
      AWS_VPC_K8S_PLUGIN_LOG_FILE:            /var/log/aws-routed-eni/plugin.log
      AWS_VPC_K8S_PLUGIN_LOG_LEVEL:           DEBUG
      DISABLE_INTROSPECTION:                  false
      DISABLE_METRICS:                        false
      DISABLE_NETWORK_RESOURCE_PROVISIONING:  false
      ENABLE_IPv4:                            false
      ENABLE_IPv6:                            true
      ENABLE_POD_ENI:                         false
      ENABLE_PREFIX_DELEGATION:               true
      MY_NODE_NAME:                            (v1:spec.nodeName)
      WARM_ENI_TARGET:                        1
      WARM_PREFIX_TARGET:                     1
      AWS_STS_REGIONAL_ENDPOINTS:             regional
      AWS_DEFAULT_REGION:                     eu-north-1
      AWS_REGION:                             eu-north-1
      AWS_ROLE_ARN:                           arn:aws:iam::254324309357:role/eksctl-test-1-addon-vpc-cni-Role1-R8JN8FC9EHA6
      AWS_WEB_IDENTITY_TOKEN_FILE:            /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    Mounts:
      /host/etc/cni/net.d from cni-net-dir (rw)
      /host/opt/cni/bin from cni-bin-dir (rw)
      /host/var/log/aws-routed-eni from log-dir (rw)
      /run/xtables.lock from xtables-lock (rw)
      /var/run/aws-node from run-dir (rw)
      /var/run/dockershim.sock from dockershim (rw)
      /var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7hzjl (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  aws-iam-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  86400
  cni-bin-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/cni/bin
    HostPathType:  
  cni-net-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/cni/net.d
    HostPathType:  
  dockershim:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/dockershim.sock
    HostPathType:  
  xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  
  log-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log/aws-routed-eni
    HostPathType:  DirectoryOrCreate
  run-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/aws-node
    HostPathType:  DirectoryOrCreate
  kube-api-access-7hzjl:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 op=Exists
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  5m26s                  default-scheduler  Successfully assigned kube-system/aws-node-mqwg7 to ip-192-168-85-232.eu-north-1.compute.internal
  Normal   Pulling    5m23s                  kubelet            Pulling image "602401143452.dkr.ecr.eu-north-1.amazonaws.com/amazon-k8s-cni-init:v1.10.2-eksbuild.1"
  Normal   Pulled     5m19s                  kubelet            Successfully pulled image "602401143452.dkr.ecr.eu-north-1.amazonaws.com/amazon-k8s-cni-init:v1.10.2-eksbuild.1" in 4.735855568s
  Normal   Created    5m19s                  kubelet            Created container aws-vpc-cni-init
  Normal   Started    5m19s                  kubelet            Started container aws-vpc-cni-init
  Normal   Pulling    5m18s                  kubelet            Pulling image "602401143452.dkr.ecr.eu-north-1.amazonaws.com/amazon-k8s-cni:v1.10.2-eksbuild.1"
  Normal   Pulled     5m17s                  kubelet            Successfully pulled image "602401143452.dkr.ecr.eu-north-1.amazonaws.com/amazon-k8s-cni:v1.10.2-eksbuild.1" in 1.339566776s
  Warning  Unhealthy  5m9s                   kubelet            Readiness probe failed: {"level":"info","ts":"2022-03-16T08:57:13.224Z","caller":"/usr/local/go/src/runtime/proc.go:255","msg":"timeout: failed to connect service \":50051\" within 5s"}
  Warning  Unhealthy  4m59s                  kubelet            Readiness probe failed: {"level":"info","ts":"2022-03-16T08:57:23.218Z","caller":"/usr/local/go/src/runtime/proc.go:255","msg":"timeout: failed to connect service \":50051\" within 5s"}
  Warning  Unhealthy  4m49s                  kubelet            Readiness probe failed: {"level":"info","ts":"2022-03-16T08:57:33.206Z","caller":"/usr/local/go/src/runtime/proc.go:255","msg":"timeout: failed to connect service \":50051\" within 5s"}
  Warning  Unhealthy  4m39s                  kubelet            Readiness probe failed: {"level":"info","ts":"2022-03-16T08:57:43.208Z","caller":"/usr/local/go/src/runtime/proc.go:255","msg":"timeout: failed to connect service \":50051\" within 5s"}
  Warning  Unhealthy  4m29s                  kubelet            Readiness probe failed: {"level":"info","ts":"2022-03-16T08:57:53.216Z","caller":"/usr/local/go/src/runtime/proc.go:255","msg":"timeout: failed to connect service \":50051\" within 5s"}
  Warning  Unhealthy  4m19s                  kubelet            Readiness probe failed: {"level":"info","ts":"2022-03-16T08:58:03.211Z","caller":"/usr/local/go/src/runtime/proc.go:255","msg":"timeout: failed to connect service \":50051\" within 5s"}
  Warning  Unhealthy  4m9s                   kubelet            Readiness probe failed: {"level":"info","ts":"2022-03-16T08:58:13.213Z","caller":"/usr/local/go/src/runtime/proc.go:255","msg":"timeout: failed to connect service \":50051\" within 5s"}
  Warning  Unhealthy  4m8s                   kubelet            Liveness probe failed: {"level":"info","ts":"2022-03-16T08:58:14.327Z","caller":"/usr/local/go/src/runtime/proc.go:255","msg":"timeout: failed to connect service \":50051\" within 5s"}
  Warning  Unhealthy  3m59s                  kubelet            Readiness probe failed: {"level":"info","ts":"2022-03-16T08:58:23.202Z","caller":"/usr/local/go/src/runtime/proc.go:255","msg":"timeout: failed to connect service \":50051\" within 5s"}
  Normal   Killing    3m48s                  kubelet            Container aws-node failed liveness probe, will be restarted
  Normal   Started    3m38s (x2 over 5m16s)  kubelet            Started container aws-node
  Normal   Created    3m38s (x2 over 5m17s)  kubelet            Created container aws-node
  Normal   Pulled     3m38s                  kubelet            Container image "602401143452.dkr.ecr.eu-north-1.amazonaws.com/amazon-k8s-cni:v1.10.2-eksbuild.1" already present on machine
  Warning  Unhealthy  19s (x33 over 3m58s)   kubelet            (combined from similar events): Readiness probe failed: {"level":"info","ts":"2022-03-16T09:02:03.204Z","caller":"/usr/local/go/src/runtime/proc.go:255","msg":"timeout: failed to connect service \":50051\" within 5s"}
```

**Comment by matti** [comment]
@achevuru I don't understand how 

https://github.com/aws/amazon-vpc-cni-k8s/blob/master/pkg/ipamd/ipamd.go#L640

can be nil when

https://github.com/aws/amazon-vpc-cni-k8s/blob/5f8ffc672072af5829c197149a9b0959314fc7e7/pkg/ipamd/ipamd.go#L376

gets called in New()

even if the envs were note set (but they are)

**Comment by matti** [comment]
@achevuru here it is, this sets it to nil if enabled (!)

https://github.com/aws/amazon-vpc-cni-k8s/blob/master/pkg/ipamd/ipamd.go#L513-L521

**Comment by matti** [comment]
so then the whole https://github.com/aws/amazon-vpc-cni-k8s/blob/5f8ffc672072af5829c197149a9b0959314fc7e7/cmd/aws-k8s-agent/main.go#L66 is null

**Comment by achevuru** [comment]
@[matti](https://github.com/matti) IPv6 is only supported in [Prefix Assignment/Delegation mode](https://github.com/aws/amazon-vpc-cni-k8s#vpc-cni-feature-matrix). Prefix Delegation is only supported on Nitro instances and CNI relies on `Hypervisor` [type to be `nitro` ](https://github.com/aws/amazon-vpc-cni-k8s/blob/611d880b538df8456036680d49877fd69d02466b/pkg/ipamd/ipamd.go#L2184)to determine if an instance is capable of supporting this feature. Hypervisor field is missing in the describe instance o/p for bare metal instances and so CNI will assume they are non nitro and will exit in IPv6 mode. In IPv4 mode, if Prefix Delegation is enabled it will print a warning message and switch to Secondary IP mode. We are working with EC2/VPC team to see how we can identify bare metal instances that support Prefix Delegation feature and we will address it soon.

**Comment by matti** [comment]
@achevuru so that is the reason for metal instances, then why #1935 ?

**Comment by matti** [comment]
>so that is the reason for metal instances, then why https://github.com/aws/amazon-vpc-cni-k8s/issues/1935 ?

because of nitro hypervisor.
