### ISSUE TITLE
aws-node amazon-k8s-cni:v1.10.2-eksbuild.1 fails on non nitro instances

### ISSUE THREAD

**Issue by matti** [aws/amazon-vpc-cni-k8s#1935]
**What happened**:

Launching instances on c5a.12xlarge fails to start / register in EKS - similar to #1929

**Attach logs**

logs from root session, the node is not present in EKS:

```
root@ip-192-168-35-188 bin]# docker logs -f dcf79a273963
{"level":"info","ts":"2022-03-19T13:09:32.020Z","caller":"entrypoint.sh","msg":"Validating env variables ..."}
{"level":"info","ts":"2022-03-19T13:09:32.021Z","caller":"entrypoint.sh","msg":"Install CNI binaries.."}
{"level":"info","ts":"2022-03-19T13:09:32.039Z","caller":"entrypoint.sh","msg":"Starting IPAM daemon in the background ... "}
{"level":"info","ts":"2022-03-19T13:09:32.044Z","caller":"entrypoint.sh","msg":"Checking for IPAM connectivity ... "}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x39 pc=0x55dfbdf3f3f8]

goroutine 366 [running]:
github.com/aws/amazon-vpc-cni-k8s/pkg/ipamd.(*IPAMContext).StartNodeIPPoolManager(0x0)
        /go/src/github.com/aws/amazon-vpc-cni-k8s/pkg/ipamd/ipamd.go:640 +0x18
created by main._main
        /go/src/github.com/aws/amazon-vpc-cni-k8s/cmd/aws-k8s-agent/main.go:64 +0x2bb
{"level":"info","ts":"2022-03-19T13:09:34.053Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-03-19T13:09:36.061Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-03-19T13:09:38.070Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-03-19T13:09:40.078Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-03-19T13:09:42.086Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
```

**What you expected to happen**:

Node to become healthy

**How to reproduce it (as minimally and precisely as possible)**:

managed nodegroup wtih c5a.12xlarge (or maybe some other 48 core machine)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21
- CNI Version aws-node amazon-k8s-cni:v1.10.2-eksbuild.1
- OS (e.g: `cat /etc/os-release`): 
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
- Kernel (e.g. `uname -a`): `Linux ip-192-168-0-194.eu-north-1.compute.internal 5.4.181-99.354.amzn2.x86_64 #1 SMP Wed Mar 2 18:50:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by jayanthvn** [comment]
This doesn't look like #1929 since the instance is marked as nitro - https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.10.2/pkg/awsutils/vpc_ip_resource_limit.go#L49. Can you please share ipamd.log?

**Comment by matti** [comment]
@jayanthvn sure, from where do I get it?

**Comment by matti** [comment]
and since this fails *always* I'm going to create a new EKS cluster with instance selector 48cpu managed nodegroup and fetch it from there once I know what to fetch.

**Comment by achevuru** [comment]
@matti I just tried creating both IPv4 and IPv6 nodegroups with`c5a.12xlarge` instances and I didn't run in to any issues. I was able to schedule pods as well in both IPv4 and IPv6 modes. Please check if you're using the correct manifest for 1.10.x versions. You can send the clusterArn to `k8s-awscni-triage@amazon.com` and we can check as well.

**Comment by matti** [comment]
Since I'm using eksctl, the manifest should be correct and other nodegroups launch

**Comment by matti** [comment]
@achevuru just sent email there with a cluster that is currently creating nodegroups for long time even without this instance type. I have a retry logic which eventually makes nodegroups to become healthy.

I'm going to start another cluster with this specific type and send that too.

**Comment by matti** [comment]
the one I sent is just deleting the nodegroup because it failed to become online (same stacktrace as in the first post of this issue)

can you point me to the ipamd.log, where is it and I'll send it.

**Comment by matti** [comment]
>can you point me to the ipamd.log, where is it and I'll send it.

https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/troubleshooting.md#debugging-logs-are-stored-in

found it - one node is again in this state, going in there now

**Comment by matti** [comment]
```
root@ip-192-168-24-106 bin]# docker ps
CONTAINER ID   IMAGE                                                                   COMMAND                  CREATED          STATUS          PORTS     NAMES
02abc4964983   724a7957db4b                                                            "/app/entrypoint.sh"     21 seconds ago   Up 21 seconds             k8s_aws-node_aws-node-z5dg6_kube-system_5f177ebb-ca7f-48b7-a14f-4cc396da0e3d_1
3e252cbf89ba   602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/kube-proxy             "kube-proxy --v=2 --…"   2 minutes ago    Up 2 minutes              k8s_kube-proxy_kube-proxy-5txwg_kube-system_f525a0a4-a388-47e8-9805-ea0ba037c1e2_0
58457e0a4a97   602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause:3.1-eksbuild.1   "/pause"                 2 minutes ago    Up 2 minutes              k8s_POD_aws-node-z5dg6_kube-system_5f177ebb-ca7f-48b7-a14f-4cc396da0e3d_0
c7544a99d029   602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause:3.1-eksbuild.1   "/pause"                 2 minutes ago    Up 2 minutes              k8s_POD_kube-proxy-5txwg_kube-system_f525a0a4-a388-47e8-9805-ea0ba037c1e2_0
```

```
[root@ip-192-168-24-106 bin]# docker logs -f 02abc4964983
{"level":"info","ts":"2022-03-20T17:50:34.392Z","caller":"entrypoint.sh","msg":"Validating env variables ..."}
{"level":"info","ts":"2022-03-20T17:50:34.394Z","caller":"entrypoint.sh","msg":"Install CNI binaries.."}
{"level":"info","ts":"2022-03-20T17:50:34.412Z","caller":"entrypoint.sh","msg":"Starting IPAM daemon in the background ... "}
{"level":"info","ts":"2022-03-20T17:50:34.414Z","caller":"entrypoint.sh","msg":"Checking for IPAM connectivity ... "}
I0320 17:50:36.304462      12 request.go:621] Throttling request took 1.044840409s, request: GET:https://[fdcf:b2b5:fa39::1]:443/apis/extensions/v1beta1?timeout=32s
{"level":"info","ts":"2022-03-20T17:50:36.422Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-03-20T17:50:38.431Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x39 pc=0x557b4c24e3f8]

goroutine 618 [running]:
github.com/aws/amazon-vpc-cni-k8s/pkg/ipamd.(*IPAMContext).StartNodeIPPoolManager(0xc00047b320)
        /go/src/github.com/aws/amazon-vpc-cni-k8s/pkg/ipamd/ipamd.go:640 +0x18
created by main._main
        /go/src/github.com/aws/amazon-vpc-cni-k8s/cmd/aws-k8s-agent/main.go:64 +0x2bb
{"level":"info","ts":"2022-03-20T17:50:40.439Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-03-20T17:50:42.448Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-03-20T17:50:44.456Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-03-20T17:50:46.464Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-03-20T17:50:48.473Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-03-20T17:50:50.481Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-03-20T17:50:52.490Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-03-20T17:50:54.499Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-03-20T17:50:56.507Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-03-20T17:50:58.517Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-03-20T17:51:00.525Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-03-20T17:51:02.533Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-03-20T17:51:04.542Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-03-20T17:51:06.553Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
```

```
[root@ip-192-168-24-106 bin]# cat /var/log/aws-routed-eni/ipamd.log
{"level":"info","ts":"2022-03-20T17:48:56.540Z","caller":"aws-k8s-agent/main.go:27","msg":"Starting L-IPAMD   ..."}
{"level":"info","ts":"2022-03-20T17:48:56.541Z","caller":"aws-k8s-agent/main.go:42","msg":"Testing communication with server"}
{"level":"info","ts":"2022-03-20T17:48:56.552Z","caller":"aws-k8s-agent/main.go:42","msg":"Successful communication with the Cluster! Cluster Version is: v1.21+. git version: v1.21.5-eks-bc4871b. git tree state: clean. commit: 5236faf39f1b7a7dabea8df12726f25608131aa9. platform: linux/amd64"}
{"level":"warn","ts":"2022-03-20T17:49:02.362Z","caller":"awssession/session.go:64","msg":"HTTP_TIMEOUT env is not set or set to less than 10 seconds, defaulting to httpTimeout to 10sec"}
{"level":"debug","ts":"2022-03-20T17:49:02.365Z","caller":"ipamd/ipamd.go:380","msg":"Discovered region: us-east-1"}
{"level":"info","ts":"2022-03-20T17:49:02.365Z","caller":"ipamd/ipamd.go:380","msg":"Custom networking enabled false"}
{"level":"debug","ts":"2022-03-20T17:49:02.366Z","caller":"awsutils/awsutils.go:407","msg":"Found availability zone: us-east-1b "}
{"level":"debug","ts":"2022-03-20T17:49:02.368Z","caller":"awsutils/awsutils.go:407","msg":"Discovered the instance primary IPv4 address: 192.168.24.106"}
{"level":"debug","ts":"2022-03-20T17:49:02.369Z","caller":"awsutils/awsutils.go:407","msg":"Found instance-id: i-0b4b51f482d11bd16 "}
{"level":"debug","ts":"2022-03-20T17:49:02.370Z","caller":"awsutils/awsutils.go:407","msg":"Found instance-type: t2.medium "}
{"level":"debug","ts":"2022-03-20T17:49:02.372Z","caller":"awsutils/awsutils.go:407","msg":"Found primary interface's MAC address: 0e:5c:f3:c9:20:85"}
{"level":"debug","ts":"2022-03-20T17:49:02.373Z","caller":"awsutils/awsutils.go:407","msg":"eni-038ab989b429dad3a is the primary ENI of this instance"}
{"level":"debug","ts":"2022-03-20T17:49:02.375Z","caller":"awsutils/awsutils.go:407","msg":"Found subnet-id: subnet-058592ea3d0bd078d "}
{"level":"debug","ts":"2022-03-20T17:49:02.375Z","caller":"ipamd/ipamd.go:389","msg":"Using WARM_ENI_TARGET 1"}
{"level":"debug","ts":"2022-03-20T17:49:02.375Z","caller":"ipamd/ipamd.go:392","msg":"Using WARM_PREFIX_TARGET 1"}
{"level":"debug","ts":"2022-03-20T17:49:02.375Z","caller":"ipamd/ipamd.go:2171","msg":"Instance hypervisor family xen"}
{"level":"error","ts":"2022-03-20T17:49:02.375Z","caller":"ipamd/ipamd.go:406","msg":"Prefix Delegation is not supported on non-nitro instance t2.medium. IPv6 is only supported in Prefix delegation Mode. "}
{"level":"info","ts":"2022-03-20T17:49:02.375Z","caller":"aws-k8s-agent/main.go:73","msg":"Serving RPC Handler version  on 127.0.0.1:50051"}
{"level":"info","ts":"2022-03-20T17:49:02.375Z","caller":"awsutils/awsutils.go:1592","msg":"Will attempt to clean up AWS CNI leaked ENIs after waiting 4m41s."}
{"level":"info","ts":"2022-03-20T17:49:02.375Z","caller":"runtime/asm_amd64.s:1581","msg":"Serving metrics on port 61678"}
{"level":"info","ts":"2022-03-20T17:49:02.375Z","caller":"runtime/asm_amd64.s:1581","msg":"Setting up shutdown hook."}
{"level":"info","ts":"2022-03-20T17:49:02.375Z","caller":"ipamd/introspect.go:62","msg":"Serving introspection endpoints on 127.0.0.1:61679"}
{"level":"info","ts":"2022-03-20T17:50:34.441Z","caller":"aws-k8s-agent/main.go:27","msg":"Starting L-IPAMD   ..."}
{"level":"info","ts":"2022-03-20T17:50:34.442Z","caller":"aws-k8s-agent/main.go:42","msg":"Testing communication with server"}
{"level":"info","ts":"2022-03-20T17:50:34.452Z","caller":"aws-k8s-agent/main.go:42","msg":"Successful communication with the Cluster! Cluster Version is: v1.21+. git version: v1.21.5-eks-bc4871b. git tree state: clean. commit: 5236faf39f1b7a7dabea8df12726f25608131aa9. platform: linux/amd64"}
{"level":"warn","ts":"2022-03-20T17:50:40.262Z","caller":"awssession/session.go:64","msg":"HTTP_TIMEOUT env is not set or set to less than 10 seconds, defaulting to httpTimeout to 10sec"}
{"level":"debug","ts":"2022-03-20T17:50:40.265Z","caller":"ipamd/ipamd.go:380","msg":"Discovered region: us-east-1"}
{"level":"info","ts":"2022-03-20T17:50:40.265Z","caller":"ipamd/ipamd.go:380","msg":"Custom networking enabled false"}
{"level":"debug","ts":"2022-03-20T17:50:40.266Z","caller":"awsutils/awsutils.go:407","msg":"Found availability zone: us-east-1b "}
{"level":"debug","ts":"2022-03-20T17:50:40.268Z","caller":"awsutils/awsutils.go:407","msg":"Discovered the instance primary IPv4 address: 192.168.24.106"}
{"level":"debug","ts":"2022-03-20T17:50:40.269Z","caller":"awsutils/awsutils.go:407","msg":"Found instance-id: i-0b4b51f482d11bd16 "}
{"level":"debug","ts":"2022-03-20T17:50:40.270Z","caller":"awsutils/awsutils.go:407","msg":"Found instance-type: t2.medium "}
{"level":"debug","ts":"2022-03-20T17:50:40.271Z","caller":"awsutils/awsutils.go:407","msg":"Found primary interface's MAC address: 0e:5c:f3:c9:20:85"}
{"level":"debug","ts":"2022-03-20T17:50:40.272Z","caller":"awsutils/awsutils.go:407","msg":"eni-038ab989b429dad3a is the primary ENI of this instance"}
{"level":"debug","ts":"2022-03-20T17:50:40.273Z","caller":"awsutils/awsutils.go:407","msg":"Found subnet-id: subnet-058592ea3d0bd078d "}
{"level":"debug","ts":"2022-03-20T17:50:40.273Z","caller":"ipamd/ipamd.go:389","msg":"Using WARM_ENI_TARGET 1"}
{"level":"debug","ts":"2022-03-20T17:50:40.273Z","caller":"ipamd/ipamd.go:392","msg":"Using WARM_PREFIX_TARGET 1"}
{"level":"debug","ts":"2022-03-20T17:50:40.273Z","caller":"ipamd/ipamd.go:2171","msg":"Instance hypervisor family xen"}
{"level":"error","ts":"2022-03-20T17:50:40.273Z","caller":"ipamd/ipamd.go:406","msg":"Prefix Delegation is not supported on non-nitro instance t2.medium. IPv6 is only supported in Prefix delegation Mode. "}
{"level":"info","ts":"2022-03-20T17:50:40.273Z","caller":"aws-k8s-agent/main.go:73","msg":"Serving RPC Handler version  on 127.0.0.1:50051"}
{"level":"info","ts":"2022-03-20T17:50:40.273Z","caller":"runtime/asm_amd64.s:1581","msg":"Setting up shutdown hook."}
{"level":"info","ts":"2022-03-20T17:50:40.273Z","caller":"awsutils/awsutils.go:1592","msg":"Will attempt to clean up AWS CNI leaked ENIs after waiting 4m41s."}
```

**Comment by achevuru** [comment]
```
{"level":"debug","ts":"2022-03-20T17:50:40.273Z","caller":"ipamd/ipamd.go:2171","msg":"Instance hypervisor family xen"}
{"level":"error","ts":"2022-03-20T17:50:40.273Z","caller":"ipamd/ipamd.go:406","msg":"Prefix Delegation is not supported on non-nitro instance t2.medium. IPv6 is only supported in Prefix delegation Mode. "}
```

**Comment by jayanthvn** [comment]
Hi, the instance type here is t2 medium and is non nitro which doesn't support PD.

**Comment by matti** [comment]
okay.png

this makes using instance selector pretty useless since it returns t2.medium with cpu 2 and 4gb ram.

**Comment by matti** [comment]
how to use https://github.com/aws/amazon-ec2-instance-selector so that it only returns instances that support PD?

**Comment by achevuru** [comment]
Not sure how `eksctl` is allowing the use to bootstrap an IPv6 NG with Non-nitro instances. I believe `eksctl` only allows Managed Nodegroups with IPv6 and if we attempt to create a v6 nodegroup from EKS console, it throws an error saying the instance can't be used because it is non-nitro. I see the same message even for `c5.metal` but it appears that eksctl allowed it to go through for v6 ng.

**Comment by matti** [comment]
or, how to even know which instances would work? I'd imagine that this would be a perfrect usecase for ec2-instance-selector to filter out

**Comment by achevuru** [comment]
List of Nitro Instances - https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html#ec2-nitro-instances

**Comment by achevuru** [comment]
@matti Not really famiilar with ec2-instance-selector. Possible they don't have a way to filter out the instances by hypervisor family. Will check once and will share if there is a way to do it.

**Comment by matti** [comment]
```
Usage:
  ec2-instance-selector [flags]

Examples:
ec2-instance-selector --vcpus 4 --region us-east-2 --availability-zones us-east-2b
ec2-instance-selector --memory-min 4 --memory-max 8 --vcpus-min 4 --vcpus-max 8 --region us-east-2

Filter Flags:
...
      --hypervisor string                 Hypervisor: [xen or nitro]
```

**Comment by achevuru** [comment]
@matti Was just going through the docs as well and found that flag as well. So, is it returning you a non-nitro instance, even after specifying the `hypervisor` flag to be `nitro`? If so, might be a bug with ec2-instance-selector then..

**Comment by matti** [comment]
it works:

without hypervisor=nitro:

```
$ ec2-instance-selector --region=us-east-1 --vcpus=2 --memory=4 --cpu-architecture "amd64"
c5.large
c5a.large
c5ad.large
c5d.large
c6a.large
c6i.large
t2.medium
t3.medium
t3a.medium
```

with:
```
$ ec2-instance-selector --region=us-east-1 --vcpus=2 --memory=4 --hypervisor nitro --cpu-architecture "x86_64"
c5.large
c5a.large
c5ad.large
c5d.large
c6a.large
c6i.large
t3.medium
t3a.medium
```

**Comment by matti** [comment]
workarounded: https://github.com/matti/eksler/blob/124ed6943500c797d6a03b121707a87c9a055042/bin/eksler#L328

btw, ec2-instance-selector has some "Suite Flags":

```
--service string              Filter instance types based on service support (Example: eks, eks-20201211, or emr-5.20.0)
```

but
```
ec2-instance-selector --region us-east-1 --vcpus 2 --memory 4 --service eks
```

returns t2.medium, so not sure what's the point of that suite flag OR if it's really up to date

**Comment by achevuru** [comment]
VPC CNI v1.10.x will not bootstrap on Non-Nitro instances in IPv6 mode and this is by design as we don't support IPv6 on these instances. Should work without any issue in IPv4 mode.

**Comment by matti** [comment]
yes, just changed the title for history.
